# Generated by Django 5.2.6 on 2025-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
