# Generated by Django 5.2.6 on 2025-10-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_unique_product_sold_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.CharField(max_length=10)),
                ('inches', models.CharField(max_length=20)),
                ('standard_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='allow_custom_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='head_sizes',
            field=models.ManyToManyField(blank=True, to='store.headsize'),
        ),
    ]
