# Generated by Django 5.2.6 on 2025-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_headsize_product_allow_custom_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this product on the homepage featured section', verbose_name='Featured on Homepage'),
        ),
    ]
