# Generated by Django 5.2.6 on 2025-12-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
