# Generated by Django 5.2.6 on 2025-09-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
